/**
 * Looker API 3.0 Reference
 * ### Authorization  The Looker API uses Looker **API3** credentials for authorization and access control. Looker admins can create API3 credentials on Looker's **Admin/Users** page. Pass API3 credentials to the **_/login** endpoint to obtain a temporary access_token. Include that access_token in the Authorization header of Looker API requests. For details, see [Looker API Authorization](https://looker.com/docs/r/api/authorization)  ### Client SDKs  The Looker API is a RESTful system that should be usable by any programming language capable of making HTTPS requests. Client SDKs for a variety of programming languages can be generated from the Looker API's Swagger JSON metadata to streamline use of the Looker API in your applications. A client SDK for Ruby is available as an example. For more information, see [Looker API Client SDKs](https://looker.com/docs/r/api/client_sdks)  ### Try It Out!  The 'api-docs' page served by the Looker instance includes 'Try It Out!' buttons for each API method. After logging in with API3 credentials, you can use the \"Try It Out!\" buttons to call the API directly from the documentation page to interactively explore API features and responses.  ### Versioning  Future releases of Looker will expand this API release-by-release to securely expose more and more of the core power of Looker to API client applications. API endpoints marked as \"beta\" may receive breaking changes without warning. Stable (non-beta) API endpoints should not receive breaking changes in future releases. For more information, see [Looker API Versioning](https://looker.com/docs/r/api/versioning) 
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

import java.util.Date

case class Dashboard (
  // Unique Id
  id: Option[String] = None,
  // Id of content metadata
  contentMetadataId: Option[Long] = None,
  // Content Favorite Id
  contentFavoriteId: Option[Long] = None,
  // Number of times viewed in the Looker web UI
  viewCount: Option[Long] = None,
  // Time the dashboard was last accessed
  lastAccessedAt: Option[Date] = None,
  // Number of times favorited
  favoriteCount: Option[Long] = None,
  // Id of User
  userId: Option[Long] = None,
  // Look Title
  title: Option[String] = None,
  // Description
  description: Option[String] = None,
  // Is Read-only
  readonly: Option[Boolean] = None,
  // Is Hidden
  hidden: Option[Boolean] = None,
  // Refresh Interval
  refreshInterval: Option[String] = None,
  // Refresh Interval as Integer
  refreshIntervalToI: Option[Long] = None,
  // Space
  space: Option[SpaceBase] = None,
  // configuration option that governs how dashboard loading will happen.
  loadConfiguration: Option[String] = None,
  // Model
  model: Option[LookModel] = None,
  // Id of Space
  spaceId: Option[String] = None,
  // Elements
  dashboardElements: Option[List[DashboardElement]] = None,
  // Layouts
  dashboardLayouts: Option[List[DashboardLayout]] = None,
  // Filters
  dashboardFilters: Option[List[DashboardFilter]] = None,
  // Time last viewed in the Looker web UI
  lastViewedAt: Option[Date] = None,
  // Background color
  backgroundColor: Option[String] = None,
  // Show title
  showTitle: Option[Boolean] = None,
  // Title color
  titleColor: Option[String] = None,
  // Show filters bar.  **Security Note:** This property only affects the *cosmetic* appearance of the dashboard, not a user's ability to access data. Hiding the filters bar does **NOT** prevent users from changing filters by other means. For information on how to set up secure data access control policies, see [Control User Access to Data](https://docs.looker.com/admin-options/tutorials/permissions#control_user_access_to_data)
  showFiltersBar: Option[Boolean] = None,
  // Tile background color
  tileBackgroundColor: Option[String] = None,
  // Tile text color
  tileTextColor: Option[String] = None,
  // Color of text on text tiles
  textTileTextColor: Option[String] = None,
  // Id of User that last updated the dashboard.
  lastUpdaterId: Option[Long] = None,
  // Id of User that deleted the dashboard.
  deleterId: Option[Long] = None,
  // Whether or not a dashboard is deleted.
  deleted: Option[Boolean] = None,
  // Time that the Dashboard was created.
  createdAt: Option[Date] = None,
  // Time that the Dashboard was deleted.
  deletedAt: Option[Date] = None,
  // Timezone in which the Dashboard will run by default.
  queryTimezone: Option[String] = None,
  // Relative path of URI of LookML file to edit the dashboard (LookML dashboard only).
  editUri: Option[String] = None,
  // Operations the current user is able to perform on this object
  can: Option[Map[String, Boolean]] = None
)

