/**
 * Looker API 3.0 Reference
 * ### Authorization  The Looker API uses Looker **API3** credentials for authorization and access control. Looker admins can create API3 credentials on Looker's **Admin/Users** page. Pass API3 credentials to the **_/login** endpoint to obtain a temporary access_token. Include that access_token in the Authorization header of Looker API requests. For details, see [Looker API Authorization](https://looker.com/docs/r/api/authorization)  ### Client SDKs  The Looker API is a RESTful system that should be usable by any programming language capable of making HTTPS requests. Client SDKs for a variety of programming languages can be generated from the Looker API's Swagger JSON metadata to streamline use of the Looker API in your applications. A client SDK for Ruby is available as an example. For more information, see [Looker API Client SDKs](https://looker.com/docs/r/api/client_sdks)  ### Try It Out!  The 'api-docs' page served by the Looker instance includes 'Try It Out!' buttons for each API method. After logging in with API3 credentials, you can use the \"Try It Out!\" buttons to call the API directly from the documentation page to interactively explore API features and responses.  ### Versioning  Future releases of Looker will expand this API release-by-release to securely expose more and more of the core power of Looker to API client applications. API endpoints marked as \"beta\" may receive breaking changes without warning. Stable (non-beta) API endpoints should not receive breaking changes in future releases. For more information, see [Looker API Versioning](https://looker.com/docs/r/api/versioning) 
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class LookmlModelExploreField (
  // The appropriate horizontal text alignment the values of this field shoud be displayed in. Valid values are: \"left\", \"right\".
  align: Option[String] = None,
  // Whether it's possible to filter on this field.
  canFilter: Option[Boolean] = None,
  // Field category Valid values are: \"parameter\", \"filter\", \"measure\", \"dimension\".
  category: Option[String] = None,
  // The default value that this field uses when filtering. Null if there is no default value.
  defaultFilterValue: Option[String] = None,
  // Description
  description: Option[String] = None,
  // An array enumerating all the possible values that this field can contain. When null, there is no limit to the set of possible values this field can contain.
  enumerations: Option[List[LookmlModelExploreFieldEnumeration]] = None,
  // An error message indicating a problem with the definition of this field. If there are no errors, this will be null.
  error: Option[String] = None,
  // A label creating a grouping of fields. All fields with this label should be presented together when displayed in a UI.
  fieldGroupLabel: Option[String] = None,
  // When presented in a field group via field_group_label, a shorter name of the field to be displayed in that context.
  fieldGroupVariant: Option[String] = None,
  // The style of dimension fill that is possible for this field. Null if no dimension fill is possible. Valid values are: \"enumeration\", \"range\".
  fillStyle: Option[String] = None,
  // An offset (in months) from the calendar start month to the fiscal start month defined in the LookML model this field belongs to.
  fiscalMonthOffset: Option[Long] = None,
  // Whether this field has a set of allowed_values specified in LookML.
  hasAllowedValues: Option[Boolean] = None,
  // Whether this field should be hidden from the user interface.
  hidden: Option[Boolean] = None,
  // Whether this field is a filter.
  isFilter: Option[Boolean] = None,
  // Whether this field represents a fiscal time value.
  isFiscal: Option[Boolean] = None,
  // Whether this field is of a type that represents a numeric value.
  isNumeric: Option[Boolean] = None,
  // Whether this field is of a type that represents a time value.
  isTimeframe: Option[Boolean] = None,
  // Whether this field can be time filtered.
  canTimeFilter: Option[Boolean] = None,
  // Details on the time interval this field represents, if it is_timeframe.
  timeInterval: Option[LookmlModelExploreFieldTimeInterval] = None,
  // Fully-qualified human-readable label of the field.
  label: Option[String] = None,
  // The name of the parameter that will provide a parameterized label for this field, if available in the current context.
  labelFromParameter: Option[String] = None,
  // The human-readable label of the field, without the view label.
  labelShort: Option[String] = None,
  // A URL linking to the definition of this field in the LookML IDE.
  lookmlLink: Option[String] = None,
  // If applicable, a map layer this field is associated with.
  mapLayer: Option[LookmlModelExploreFieldMapLayer] = None,
  // Whether this field is a measure.
  measure: Option[Boolean] = None,
  // Fully-qualified name of the field.
  name: Option[String] = None,
  // Whether this field is a parameter.
  parameter: Option[Boolean] = None,
  // Whether this field can be removed from a query.
  permanent: Option[Boolean] = None,
  // Whether or not the field represents a primary key.
  primaryKey: Option[Boolean] = None,
  // The name of the project this field is defined in.
  projectName: Option[String] = None,
  // When true, it's not possible to re-sort this field's values without re-running the SQL query, due to database logic that affects the sort.
  requiresRefreshOnSort: Option[Boolean] = None,
  // The LookML scope this field belongs to. The scope is typically the field's view.
  scope: Option[String] = None,
  // Whether this field can be sorted.
  sortable: Option[Boolean] = None,
  // The path portion of source_file_path.
  sourceFile: Option[String] = None,
  // The fully-qualified path of the project file this field is defined in.
  sourceFilePath: Option[String] = None,
  // SQL expression as defined in the LookML model. This will be null if the current user does not have the see_lookml permission for the field's model.
  sql: Option[String] = None,
  // An array of conditions and values that make up a SQL Case expression, as defined in the LookML model. This will be null if the current user does not have the see_lookml permission for the field's model.
  sqlCase: Option[List[LookmlModelExploreFieldSqlCase]] = None,
  // The name of the dimension to base suggest queries from.
  suggestDimension: Option[String] = None,
  // The name of the explore to base suggest queries from.
  suggestExplore: Option[String] = None,
  // Whether or not suggestions are possible for this field.
  suggestable: Option[Boolean] = None,
  // If available, a list of suggestions for this field. For most fields, a suggest query is a more appropriate way to get an up-to-date list of suggestions. Or use enumerations to list all the possible values.
  suggestions: Option[List[String]] = None,
  // An array of arbitrary string tags provided in the model for this field.
  tags: Option[List[String]] = None,
  // The LookML type of the field.
  `type`: Option[String] = None,
  // An array of user attribute types that are allowed to be used in filters on this field. Valid values are: \"advanced_filter_string\", \"advanced_filter_number\", \"advanced_filter_datetime\", \"string\", \"number\", \"datetime\", \"yesno\", \"zipcode\".
  userAttributeFilterTypes: Option[List[String]] = None,
  // If specified, the LookML value format string for formatting values of this field.
  valueFormat: Option[String] = None,
  // The name of the view this field belongs to.
  view: Option[String] = None,
  // The human-readable label of the view the field belongs to.
  viewLabel: Option[String] = None,
  // Whether this field was specified in \"dynamic_fields\" and is not part of the model.
  dynamic: Option[Boolean] = None,
  // The name of the starting day of the week. Valid values are: \"monday\", \"tuesday\", \"wednesday\", \"thursday\", \"friday\", \"saturday\", \"sunday\".
  weekStartDay: Option[String] = None
)

