/**
 * Looker API 3.0 Reference
 * ### Authorization  The Looker API uses Looker **API3** credentials for authorization and access control. Looker admins can create API3 credentials on Looker's **Admin/Users** page. Pass API3 credentials to the **_/login** endpoint to obtain a temporary access_token. Include that access_token in the Authorization header of Looker API requests. For details, see [Looker API Authorization](https://looker.com/docs/r/api/authorization)  ### Client SDKs  The Looker API is a RESTful system that should be usable by any programming language capable of making HTTPS requests. Client SDKs for a variety of programming languages can be generated from the Looker API's Swagger JSON metadata to streamline use of the Looker API in your applications. A client SDK for Ruby is available as an example. For more information, see [Looker API Client SDKs](https://looker.com/docs/r/api/client_sdks)  ### Try It Out!  The 'api-docs' page served by the Looker instance includes 'Try It Out!' buttons for each API method. After logging in with API3 credentials, you can use the \"Try It Out!\" buttons to call the API directly from the documentation page to interactively explore API features and responses.  ### Versioning  Future releases of Looker will expand this API release-by-release to securely expose more and more of the core power of Looker to API client applications. API endpoints marked as \"beta\" may receive breaking changes without warning. Stable (non-beta) API endpoints should not receive breaking changes in future releases. For more information, see [Looker API Versioning](https://looker.com/docs/r/api/versioning) 
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class User (
  // Unique Id
  id: Option[Long] = None,
  // First name
  firstName: Option[String] = None,
  // Last name
  lastName: Option[String] = None,
  // Full name for display (available only if both first_name and last_name are set)
  displayName: Option[String] = None,
  // EMail address
  email: Option[String] = None,
  // Account has been disabled
  isDisabled: Option[Boolean] = None,
  // URL for the avatar image (may be generic)
  avatarUrl: Option[String] = None,
  // ID string for user's home space
  homeSpaceId: Option[String] = None,
  // ID of user's personal space
  personalSpaceId: Option[Long] = None,
  // (Embed only) ID of user's group space based on the external_group_id optionally specified during embed user login
  embedGroupSpaceId: Option[Long] = None,
  // Model access filters.
  accessFilters: Option[List[AccessFilter]] = None,
  // Email/Password login credentials
  credentialsEmail: Option[CredentialsEmail] = None,
  // Two-factor credentials
  credentialsTotp: Option[CredentialsTotp] = None,
  // LDAP credentials
  credentialsLdap: Option[CredentialsLDAP] = None,
  // Google auth credentials
  credentialsGoogle: Option[CredentialsGoogle] = None,
  // Saml auth credentials
  credentialsSaml: Option[CredentialsSaml] = None,
  // OpenID Connect auth credentials
  credentialsOidc: Option[CredentialsOIDC] = None,
  // API user credentials. NO LONGER SUPPORTED.
  credentialsApi: Option[CredentialsApi] = None,
  // API 3 credentials
  credentialsApi3: Option[List[CredentialsApi3]] = None,
  // Embed credentials
  credentialsEmbed: Option[List[CredentialsEmbed]] = None,
  // LookerOpenID credentials. Used for login by Looker Analysts
  credentialsLookerOpenid: Option[CredentialsLookerOpenid] = None,
  // Active sessions
  sessions: Option[List[Session]] = None,
  // Array of ids of the roles for this user
  roleIds: Option[List[Long]] = None,
  // Array of ids of the groups for this user
  groupIds: Option[List[Long]] = None,
  // User is identified as an employee of Looker
  presumedLookerEmployee: Option[Boolean] = None,
  // User is identified as an employee of Looker who has been verified via Looker corporate authentication
  verifiedLookerEmployee: Option[Boolean] = None,
  // Array of strings representing the Looker versions that this user has used (this only goes back as far as '3.54.0')
  lookerVersions: Option[List[String]] = None,
  // Per user dictionary of undocumented state information owned by the Looker UI.
  uiState: Option[Map[String, String]] = None,
  // User's preferred locale. User locale takes precedence over Looker's system-wide default locale. Locale determines language of display strings and date and numeric formatting in API responses. Locale string must be a 2 letter language code or a combination of language code and region code: 'en' or 'en-US', for example.
  locale: Option[String] = None,
  // Link to get this item
  url: Option[String] = None,
  // Operations the current user is able to perform on this object
  can: Option[Map[String, Boolean]] = None
)

